source "https://github.com/CocoaPods/Specs.git"
platform :ios, "9.0"
use_frameworks!

target "LoveFreshBeen-swift" do
pod "SnapKit"
pod "Kingfisher"
pod "SVProgressHUD"
pod "FDFullscreenPopGesture", "~> 1.1"
pod "Alamofire"
pod "SwiftyJSON"

end